"""Write the agent-test suite: public tasks (catalog tag) + private graders (sidecar).

    python tools/agent_tasks.py suggestions.json   # [{name, prompt, reference_sql, ...}, ...]

Public ``{name, prompt}`` go to ``vgi_cloudflare/agent_tasks.json`` (served as the
catalog's ``vgi.agent_test_tasks``); grader fields go to ``vgi-agent-tests.yaml``,
which vgi-lint reads beside ``vgi-lint.toml`` and never exposes as metadata.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "vgi_cloudflare" / "agent_tasks.json"
SIDECAR = ROOT / "vgi-agent-tests.yaml"
GRADER_FIELDS = ("reference_sql", "check_sql", "success_criteria", "unordered", "ignore_column_names")


def _yaml_scalar(value: object) -> str:
    return json.dumps(value)  # JSON scalars are valid YAML


def write(tasks: list[dict]) -> None:
    PUBLIC.write_text(
        json.dumps([{"name": t["name"], "prompt": t["prompt"]} for t in tasks], indent=2) + "\n"
    )
    lines = [
        "# Private graders for vgi_cloudflare/agent_tasks.json, keyed by task name.",
        "# Generated by tools/agent_tasks.py; run with `vgi-lint simulate` (see vgi-lint.toml).",
        "tasks:",
    ]
    for t in tasks:
        lines.append(f"  - name: {_yaml_scalar(t['name'])}")
        for key in GRADER_FIELDS:
            if key not in t:
                continue
            value = t[key]
            if isinstance(value, str) and key.endswith("_sql"):
                lines.append(f"    {key}: |")
                lines += [f"      {line}" for line in value.strip().splitlines()]
            else:
                lines.append(f"    {key}: {_yaml_scalar(value)}")
    SIDECAR.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    write(json.loads(Path(sys.argv[1]).read_text()))
